### PR TITLE
Implemented SysCall_NumInstr

### PR DESCRIPTION
**Pull request by shikhi7**
First PR

### CODE REVIEW

**Comment by shikhi7** [comment]
note to check if this's working

**Review by RaiManish3 — CHANGES_REQUESTED** [review]
In exception.cc you cannot access the private variable "instrCount" directly. Make a function to retrieve it.

**Comment by shikhi7** [comment]
Added a new commit introducing functions. Pls check
Can use printtest or vectorsum programs under test dir to check this syscall

**Review by RaiManish3 — APPROVED** [review]
Looks good !!

**Pull request merged**
